# Generated by Django 5.1.7 on 2025-04-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
